export enum TUTORIAL_NAMES {
    income = 'income',
    obligations = 'obligations',
    expenses = 'expenses',
    welcome = 'welcome',
}
export enum ACTION_TYPES {
    PASS_TUTORIAL = 'PASS_TUTORIAL',
    ADD_PERIOD = 'ADD_PERIOD',
    ADD_INCOME = 'ADD_INCOME',
    ADD_OBLIGATION = 'ADD_OBLIGATION',
    ADD_EXPENSE = 'ADD_EXPENSE',
    UPDATE_INCOME = 'UPDATE_INCOME',
    REMOVE_INCOME = 'REMOVE_INCOME',
    UPDATE_OBLIGATION = 'UPDATE_OBLIGATION',
    REMOVE_OBLIGATION = 'REMOVE_OBLIGATION',
    UPDATE_EXPENSE = 'UPDATE_EXPENSE',
    REMOVE_EXPENSE = 'REMOVE_EXPENSE',
    SELECT_PERIOD = 'SELECT_PERIOD',
    START_NEW_MONTH = 'START_NEW_MONTH',
    LOAD_STORE = 'LOAD_STORE',
};
